spring:
  application:
    name: sealyr-cloud-bus
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      name: config-client
      label: master
      profile: dev
      discovery:
        serviceId: sealyr-cloud-config-server
server:
  port: 28087