spring:
  application:
    name: sealyr-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/forezp/SpringcloudConfig/
          searchPaths: respo
      label: master
server:
  port: 8888