spring:
  application:
    name: sealyr-cloud-netflix-zuul
server:
  port: 28085
zuul:
  routes:
    api-eureka:
      path: /api/eureka/**
      serviceId: sealyr-cloud-netflix-eureka-client
    api-hystrix:
      path: /api/hystrix/**
      serviceId: sealyr-cloud-netflix-hystrix