spring:
  application:
    name: sealyr-cloud-config-client
  cloud:
    config:
      name: config-client
      label: master
      profile: dev
      discovery:
        serviceId: sealyr-cloud-config-server
server:
  port: 28889